
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND DIVIDE EQUAL LPAREN MINUS NAME NUMBER OR PLUS RPAREN SEMI TIMES bloc : bloc statement SEMI \n    | statement SEMIstatement : NAME EQUAL expressionstatement : expressionexpression : expression PLUS expressionexpression : expression TIMES expressionexpression : expression MINUS expression\n\t\t\t\t| expression DIVIDE expressionexpression : LPAREN expression RPARENexpression : NUMBERexpression : NAMEexpression : expression AND expressionexpression : expression OR expression'
    
_lr_action_items = {'NAME':([0,1,5,8,9,10,11,12,13,14,15,18,],[3,3,17,-2,17,17,17,17,17,17,17,-1,]),'LPAREN':([0,1,5,8,9,10,11,12,13,14,15,18,],[5,5,5,-2,5,5,5,5,5,5,5,-1,]),'NUMBER':([0,1,5,8,9,10,11,12,13,14,15,18,],[6,6,6,-2,6,6,6,6,6,6,6,-1,]),'$end':([1,8,18,],[0,-2,-1,]),'SEMI':([2,3,4,6,7,17,19,20,21,22,23,24,25,26,],[8,-11,-4,-10,18,-11,-3,-5,-6,-7,-8,-12,-13,-9,]),'EQUAL':([3,],[9,]),'PLUS':([3,4,6,16,17,19,20,21,22,23,24,25,26,],[-11,10,-10,10,-11,10,10,10,10,10,10,10,-9,]),'TIMES':([3,4,6,16,17,19,20,21,22,23,24,25,26,],[-11,11,-10,11,-11,11,11,11,11,11,11,11,-9,]),'MINUS':([3,4,6,16,17,19,20,21,22,23,24,25,26,],[-11,12,-10,12,-11,12,12,12,12,12,12,12,-9,]),'DIVIDE':([3,4,6,16,17,19,20,21,22,23,24,25,26,],[-11,13,-10,13,-11,13,13,13,13,13,13,13,-9,]),'AND':([3,4,6,16,17,19,20,21,22,23,24,25,26,],[-11,14,-10,14,-11,14,14,14,14,14,14,14,-9,]),'OR':([3,4,6,16,17,19,20,21,22,23,24,25,26,],[-11,15,-10,15,-11,15,15,15,15,15,15,15,-9,]),'RPAREN':([6,16,17,20,21,22,23,24,25,26,],[-10,26,-11,-5,-6,-7,-8,-12,-13,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'bloc':([0,],[1,]),'statement':([0,1,],[2,7,]),'expression':([0,1,5,9,10,11,12,13,14,15,],[4,4,16,19,20,21,22,23,24,25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> bloc","S'",1,None,None,None),
  ('bloc -> bloc statement SEMI','bloc',3,'p_bloc','calcBase.py',52),
  ('bloc -> statement SEMI','bloc',2,'p_bloc','calcBase.py',53),
  ('statement -> NAME EQUAL expression','statement',3,'p_statement_assign','calcBase.py',57),
  ('statement -> expression','statement',1,'p_statement_expr','calcBase.py',64),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop_plus','calcBase.py',68),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop_times','calcBase.py',72),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop_divide_and_minus','calcBase.py',76),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop_divide_and_minus','calcBase.py',77),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','calcBase.py',82),
  ('expression -> NUMBER','expression',1,'p_expression_number','calcBase.py',86),
  ('expression -> NAME','expression',1,'p_expression_name','calcBase.py',90),
  ('expression -> expression AND expression','expression',3,'p_expression_binop_bool','calcBase.py',94),
  ('expression -> expression OR expression','expression',3,'p_expression_binop_bool2','calcBase.py',98),
]
